#!/bin/bash

#Edit a configuration value in a file: edit-conf file section name newValue
#Keep the old value in comment to be able to restore

confFile="$1"
section="$2"
name="$3"
value="$4"

if [ `cat $confFile | grep -c "^\s*$name\s*="` -gt 0 ];
then
	# Option exists
	sedCommand="s/^\s*$name\s*=.*$/#jolicloud-tweaks modification:\\n#old: &\\n#new: $name=$value\\n$name=$value/"
	sed -i "$sedCommand" $confFile
else
	if [ `cat $confFile | grep -c "^\s*\[\s*$section\s*\]\s*$"` -gt 0 ];
	then
		# Section exists
		sedCommand="s/^\s*\[\s*$section\s*\]\s*$/[$section]\\n\\n#jolicloud-tweaks modification:\\n#old: \\n#new: $name=$value\\n$name=$value/"
		sed -i "$sedCommand" $confFile
	else
		# Section doesn't exist
		echo "
[$section]

#jolicloud-tweaks modification:
#old: 
#new: $name=$value
$name=$value" >> $confFile
	fi
fi

exit 0
